version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - MONGO_URI=mongodb+srv://berrichif0717:U7M4nNF6JUoi0Kq9@cluster0.rfcqlso.mongodb.net/travel?retryWrites=true&w=majority
      - REDIS_URL=redis://default:XKUeCvGRzRogGW11TCDExzI27VKAfCm1@redis-13114.c239.us-east-1-2.ec2.redns.redis-cloud.com:13114
      #- NEO4J_URI=neo4j+s://<your-neo4j-host>.databases.neo4j.io
      # - NEO4J_USER=<your-user>
      #- NEO4J_PASSWORD=<your-password>
    command: node server.js
